/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Blender.Blender;
import Cruzamento.Cruzamento;
import Cruzamento.OrderCrossOver;
import Model.Grafo;
import Model.Populacao;
import Mutacao.Mutacao;
import Mutacao.SwapMutacao;
import Selecao.Roleta;
import Selecao.Selecao;
import java.util.Locale;

/**
 *
 * @author FREE
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private Grafo custo = null;
    private int nGeracoes = 0;
    private boolean lock = false;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Grafo custo) {
        initComponents();
        this.custo = custo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbApenasPercentage = new javax.swing.JLabel();
        lbPercentage = new javax.swing.JLabel();
        btIniciar = new javax.swing.JButton();
        tfGeracoes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbApenasPercentage.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        lbApenasPercentage.setText("%");

        lbPercentage.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        lbPercentage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPercentage.setText("0");

        btIniciar.setText("Iniciar");
        btIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarActionPerformed(evt);
            }
        });

        tfGeracoes.setText("0");
        tfGeracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGeracoesActionPerformed(evt);
            }
        });

        jLabel1.setText("Geracoes");

        jLabel2.setText("OBS : Perte enter depois de digitar o numero desejado");

        jLabel3.setText("TamanhoPopulacao");

        jTextField1.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lbPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lbApenasPercentage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(28, 28, 28)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfGeracoes, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(jTextField1))
                                .addGap(113, 113, 113)))
                        .addGap(68, 68, 68))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbApenasPercentage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGeracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btIniciar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarActionPerformed
        // TODO add your handling code here:
        if (!lock)
        {
            lock = true;
            lockValues();
            forceValues();
            lbPercentage.setText("0");
            lbPercentage.paintImmediately(lbPercentage.getVisibleRect());

            Populacao test = new Populacao(100, custo);//populacao inicial
            //test.printarInformacoes();
            Cruzamento cruzamento = new OrderCrossOver(60);//cruzamento OX com 100% de chance de cruzamento
            Selecao selecao = new Selecao(100, new Roleta());//usa roleta e fitness
            Mutacao mutacao = new SwapMutacao(0.002);

            Blender prox = new Blender(test,selecao,cruzamento,mutacao,40,60,100);
            double valorAgora;
            double mudancaNecessaria = 5.00;
            double percentage;
            int total = nGeracoes;
            for (int i=0;i<total;i++)
            {
                valorAgora = Double.parseDouble( lbPercentage.getText() );
                percentage = 100*(i+1+0.00)/(total+0.00);
                //System.out.println("percentage : " + percentage);
                //System.out.println("valoragora : " + valorAgora);
                //System.out.println("percenta-valoragora : " + (percentage - valorAgora));
                if ((percentage - valorAgora) >= mudancaNecessaria)
                {
                    //System.out.println("TRUEEEEEEEEEEEEEEEEEEEEEE");
                    lbPercentage.setText(String.format(Locale.US,"%.2f",percentage));
                    lbPercentage.paintImmediately(lbPercentage.getVisibleRect());
                }
                prox.proximaGeracao(test);
            }
            //test.printarInformacoes();
            /*
            JFrame frame = new JFrame();
            JPanel panel = new GraficoJPanel(prox.getGraficodados());
            panel.setPreferredSize(new Dimension(800,600));
            panel.setBackground(Color.GRAY);
            frame.add(panel);
            frame.pack();
            ViewGlobal.centralizarJanela(frame);
            frame.setVisible(true);
            */
            GraficoFrame frame = new GraficoFrame(prox.getGraficodados());
            
            lbPercentage.setText("100");
            unlockValues();
            lock = false;
        }
        //Caminho filho1 = filhos[0];
        //Caminho filho2 = filhos[1];
    }//GEN-LAST:event_btIniciarActionPerformed

    private void forceValues()
    {
        forceGeracoes();
    }
    
    private void forceGeracoes()
    {
        try{
            int n = Integer.parseInt(tfGeracoes.getText());
            nGeracoes = n;
        }
        catch(NumberFormatException e)
        {
            tfGeracoes.setText( Integer.toString(nGeracoes ) );
        }
    }
    
    private void lockValues()
    {
        btIniciar.setEnabled(false);
        tfGeracoes.setEditable(false);
    }
    
    private void unlockValues()
    {
        btIniciar.setEnabled(true);
        tfGeracoes.setEditable(true);
    }
    
    private void tfGeracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGeracoesActionPerformed
        // TODO add your handling code here:
        forceGeracoes();
    }//GEN-LAST:event_tfGeracoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbApenasPercentage;
    private javax.swing.JLabel lbPercentage;
    private javax.swing.JTextField tfGeracoes;
    // End of variables declaration//GEN-END:variables
}
