package view;


import Model.Grafo;
import java.io.File;
import javax.swing.JFileChooser;
import processamentoArquivo.Processar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FREE
 */
public class TelaCarregar extends javax.swing.JFrame {
    JFileChooser filechooser = null;
    /**
     * Creates new form TelaInicial
     */
    public TelaCarregar() {
        initComponents();
        ViewGlobal.centralizarJanela(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCarregarNodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btCarregarNodos.setText("CarregarNodos");
        btCarregarNodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarregarNodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btCarregarNodos)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(btCarregarNodos)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCarregarNodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarregarNodosActionPerformed
        // TODO add your handling code here:
        if (filechooser==null)
        {
            filechooser = new JFileChooser();
        }
        filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        boolean dispose = false;
        int returnVal = filechooser.showOpenDialog(this);
        Grafo grafo = null;
        if (returnVal == JFileChooser.APPROVE_OPTION)
        {
            File file = filechooser.getSelectedFile();
            grafo = Processar.processar(file);
            if (grafo!=null)
            {
                System.out.println("SUCESO");
                MenuPrincipal novoMenu = new MenuPrincipal(grafo);
                novoMenu.setVisible(true);
                this.dispose();
                this.setVisible(false);
                dispose = true;
            }
        }
        else
        {
            
        }
        if (!dispose)
        {
            
        }
    }//GEN-LAST:event_btCarregarNodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCarregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCarregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCarregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCarregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCarregar().setVisible(true);
                /*
                Caminho testcaminho = Gerador.CaminhoGen.gerarRandomCaminho();
                testcaminho.printCaminho();
                if (testcaminho.validarCaminho())
                {
                    System.out.println("Caminho valido");
                }
                else
                {
                    System.out.println("Caminho invalido");
                }
                */
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCarregarNodos;
    // End of variables declaration//GEN-END:variables
}
